baseURL = "https://HNought.github.io/"
title = "HNought"
author = "Raghava"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "ezhil"
disqusShortname = "hnought-github-io"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 3

  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks/"
    weight = 4

  [[menu.main]]
    identifier = "oss"
    name = "OSS"
    url = "/oss/"
    weight = 5

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 6

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

